name: CI
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: simple-cspell
        uses: streetsidesoftware/cspell-action@v2
        with:
          paths: "**/*.md"
          config: .github/workflows/cspell.json
      
